"""Add observations and user preferences tables

Revision ID: 24a9158bd045
Revises: b5150659897f
Create Date: 2025-11-06 18:40:40.025268

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "24a9158bd045"
down_revision: str | Sequence[str] | None = "b5150659897f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preferences",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_preferences_category"), ["category"], unique=False)

    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lon", sa.Float(), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("seeing_quality", sa.Integer(), nullable=True),
        sa.Column("transparency", sa.Integer(), nullable=True),
        sa.Column("sky_brightness", sa.Float(), nullable=True),
        sa.Column("weather_notes", sa.Text(), nullable=True),
        sa.Column("telescope", sa.String(length=255), nullable=True),
        sa.Column("eyepiece", sa.String(length=255), nullable=True),
        sa.Column("filters", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("image_path", sa.String(length=1024), nullable=True),
        sa.Column("sketch_path", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_observations_object_id"), ["object_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_observations_observed_at"), ["observed_at"], unique=False)

    # Note: FTS5 tables (objects_fts*) are preserved - they are virtual tables not tracked by SQLAlchemy
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "objects_fts_config",
        sa.Column("k", sa.NullType(), nullable=False),
        sa.Column("v", sa.NullType(), nullable=True),
        sa.PrimaryKeyConstraint("k"),
    )
    op.create_table(
        "objects_fts_idx",
        sa.Column("segid", sa.NullType(), nullable=False),
        sa.Column("term", sa.NullType(), nullable=False),
        sa.Column("pgno", sa.NullType(), nullable=True),
        sa.PrimaryKeyConstraint("segid", "term"),
    )
    op.create_table(
        "objects_fts_docsize",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("sz", sa.BLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "objects_fts_data",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("block", sa.BLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "objects_fts",
        sa.Column("name", sa.NullType(), nullable=True),
        sa.Column("common_name", sa.NullType(), nullable=True),
        sa.Column("description", sa.NullType(), nullable=True),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observations_observed_at"))
        batch_op.drop_index(batch_op.f("ix_observations_object_id"))

    op.drop_table("observations")
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_preferences_category"))

    op.drop_table("user_preferences")
    # ### end Alembic commands ###
