"""Initial schema with FTS5 support

Revision ID: 565d35ca5a03
Revises: 
Create Date: 2025-11-06 18:26:18.994219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565d35ca5a03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects_fts_data')
    op.drop_table('objects_fts_config')
    op.drop_table('objects_fts')
    op.drop_table('objects_fts_docsize')
    op.drop_table('objects_fts_idx')
    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('common_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('catalog',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('ra_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('dec_degrees',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('magnitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('object_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('size_arcmin',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('constellation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('is_dynamic',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ephemeris_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('parent_planet',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_catalog'))
        batch_op.drop_index(batch_op.f('idx_constellation'))
        batch_op.drop_index(batch_op.f('idx_is_dynamic'))
        batch_op.drop_index(batch_op.f('idx_magnitude'))
        batch_op.drop_index(batch_op.f('idx_name'))
        batch_op.drop_index(batch_op.f('idx_type'))
        batch_op.create_index('idx_type_magnitude', ['object_type', 'magnitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_catalog'), ['catalog'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_constellation'), ['constellation'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_is_dynamic'), ['is_dynamic'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_magnitude'), ['magnitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_object_type'), ['object_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objects_object_type'))
        batch_op.drop_index(batch_op.f('ix_objects_name'))
        batch_op.drop_index(batch_op.f('ix_objects_magnitude'))
        batch_op.drop_index(batch_op.f('ix_objects_is_dynamic'))
        batch_op.drop_index(batch_op.f('ix_objects_constellation'))
        batch_op.drop_index(batch_op.f('ix_objects_catalog'))
        batch_op.drop_index('idx_type_magnitude')
        batch_op.create_index(batch_op.f('idx_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_magnitude'), ['magnitude'], unique=False)
        batch_op.create_index(batch_op.f('idx_is_dynamic'), ['is_dynamic'], unique=False)
        batch_op.create_index(batch_op.f('idx_constellation'), ['constellation'], unique=False)
        batch_op.create_index(batch_op.f('idx_catalog'), ['catalog'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('parent_planet',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ephemeris_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_dynamic',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('constellation',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('size_arcmin',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('object_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('magnitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('dec_degrees',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('ra_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('catalog',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('common_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)

    op.create_table('objects_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('objects_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects_fts',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('common_name', sa.NullType(), nullable=True),
    sa.Column('description', sa.NullType(), nullable=True)
    )
    op.create_table('objects_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('objects_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
