"""add_ephemeris_files_table

Revision ID: a7f3b8c9d2e1
Revises: 030d966a662d
Create Date: 2025-01-27 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a7f3b8c9d2e1"
down_revision: str | Sequence[str] | None = "030d966a662d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ephemeris_files",
        sa.Column("file_key", sa.String(length=100), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("coverage_start", sa.Integer(), nullable=False),
        sa.Column("coverage_end", sa.Integer(), nullable=False),
        sa.Column("size_mb", sa.Float(), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("contents", sa.Text(), nullable=False),
        sa.Column("use_case", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("file_key"),
    )
    with op.batch_alter_table("ephemeris_files", schema=None) as batch_op:
        batch_op.create_index("idx_coverage", ["coverage_start", "coverage_end"], unique=False)
        batch_op.create_index("idx_file_type", ["file_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_ephemeris_files_filename"), ["filename"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ephemeris_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ephemeris_files_filename"))
        batch_op.drop_index("idx_file_type")
        batch_op.drop_index("idx_coverage")
    op.drop_table("ephemeris_files")
    # ### end Alembic commands ###
