"""add_object_subtype_id_foreign_key

Revision ID: f1af6e2ecaf5
Revises: 3aa0e98edd2a
Create Date: 2025-12-26 14:56:55.079503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f1af6e2ecaf5'
down_revision: Union[str, Sequence[str], None] = '3aa0e98edd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """Check if an index exists on a table."""
    connection = op.get_bind()
    result = connection.execute(
        sa.text(
            "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name=:table AND name=:index"
        ),
        {"table": table_name, "index": index_name}
    )
    return result.fetchone() is not None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_subtype_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clusters_object_subtype_id'), ['object_subtype_id'], unique=False)
        batch_op.create_foreign_key('fk_clusters_object_subtype_id', 'object_types', ['object_subtype_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_subtype_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_double_stars_object_subtype_id'), ['object_subtype_id'], unique=False)
        batch_op.create_foreign_key('fk_double_stars_object_subtype_id', 'object_types', ['object_subtype_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('galaxies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_subtype_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_galaxies_object_subtype_id'), ['object_subtype_id'], unique=False)
        batch_op.create_foreign_key('fk_galaxies_object_subtype_id', 'object_types', ['object_subtype_id'], ['id'], ondelete='SET NULL')

    # Skip meteor_showers - index already exists with correct name

    with op.batch_alter_table('moons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_subtype_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_moons_object_subtype_id'), ['object_subtype_id'], unique=False)
        batch_op.create_foreign_key('fk_moons_object_subtype_id', 'object_types', ['object_subtype_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('nebulae', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_subtype_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nebulae_object_subtype_id'), ['object_subtype_id'], unique=False)
        batch_op.create_foreign_key('fk_nebulae_object_subtype_id', 'object_types', ['object_subtype_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_subtype_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_planets_object_subtype_id'), ['object_subtype_id'], unique=False)
        batch_op.create_foreign_key('fk_planets_object_subtype_id', 'object_types', ['object_subtype_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_subtype_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stars_object_subtype_id'), ['object_subtype_id'], unique=False)
        batch_op.create_foreign_key('fk_stars_object_subtype_id', 'object_types', ['object_subtype_id'], ['id'], ondelete='SET NULL')

    # Skip variable_stars and weather_forecast - indexes already exist with correct names

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_forecast', schema=None) as batch_op:
        if _index_exists('weather_forecast', 'idx_location_fetched'):
            batch_op.drop_index('idx_location_fetched')
        if not _index_exists('weather_forecast', 'idx_weather_location_fetched'):
            batch_op.create_index(batch_op.f('idx_weather_location_fetched'), ['latitude', 'longitude', 'fetched_at'], unique=False)

    with op.batch_alter_table('variable_stars', schema=None) as batch_op:
        if _index_exists('variable_stars', 'idx_position'):
            batch_op.drop_index('idx_position')
        if not _index_exists('variable_stars', 'idx_variable_star_position'):
            batch_op.create_index(batch_op.f('idx_variable_star_position'), ['ra_hours', 'dec_degrees'], unique=False)

    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stars_object_subtype_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stars_object_subtype_id'))
        batch_op.drop_column('object_subtype_id')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_planets_object_subtype_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_planets_object_subtype_id'))
        batch_op.drop_column('object_subtype_id')

    with op.batch_alter_table('nebulae', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nebulae_object_subtype_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_nebulae_object_subtype_id'))
        batch_op.drop_column('object_subtype_id')

    with op.batch_alter_table('moons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_moons_object_subtype_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_moons_object_subtype_id'))
        batch_op.drop_column('object_subtype_id')

    with op.batch_alter_table('meteor_showers', schema=None) as batch_op:
        if _index_exists('meteor_showers', 'idx_peak_date'):
            batch_op.drop_index('idx_peak_date')
        if not _index_exists('meteor_showers', 'idx_meteor_shower_peak_date'):
            batch_op.create_index(batch_op.f('idx_meteor_shower_peak_date'), ['peak_month', 'peak_day'], unique=False)

    with op.batch_alter_table('galaxies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_galaxies_object_subtype_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_galaxies_object_subtype_id'))
        batch_op.drop_column('object_subtype_id')

    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.drop_constraint('fk_double_stars_object_subtype_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_double_stars_object_subtype_id'))
        batch_op.drop_column('object_subtype_id')

    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clusters_object_subtype_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clusters_object_subtype_id'))
        batch_op.drop_column('object_subtype_id')

    # ### end Alembic commands ###
